config/routes.rb
SampleApp::Application.routes.draw do

  devise_for :users
  get "relationships/create"
  get "relationships/destroy"

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

	resources :users, only: [:index, :show, :destroy] do
		member do
			get :following, :followers
		end
	end
	resources :microposts, only: [:create, :destroy ]
	resources :relationships, only: [:create, :destroy ]
	
	

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.haml
%footer.footer
	%small
		%a{:href => 'http://railstutorial.org/'}
			Rails Tutorial
		by Michael Hartl and Dave McCormick
	%nav
		%ul
			%li= link_to "About", about_path
			%li= link_to "Contact", contact_path
			%li
				%a{:href => 'http://news.railstutorial.org/'}
					News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
	.navbar-inner
		.container
			= link_to "sample app", root_path, id: "logo"
			%nav
				%ul.nav.pull-right
					%li= link_to "Home", root_path
					%li= link_to "Help", help_path
					- if user_signed_in?
						%li= link_to "Users", users_path
						%li.dropdown
							%a{ :class => 'dropdown-toggle', :'data-toggle' => 'dropdown', :href => '#' }
								Account
								%b.caret
							%ul.dropdown-menu.pull-right{ :role => "menu" }
								%li= link_to "Profile", current_user
								%li= link_to "Settings", edit_user_registration_path
								%li.divider
								%li= link_to "Sign out", destroy_user_session_path, method: 'delete'
					- else
						%li= link_to "Sign in", new_user_session_path

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key,value| %>
		<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<% if (Rails.env.development? or Rails.env.test?) %>
			<%= debug(params) %>
			<%= debug(user_session) %>
		<% end %>
	</div>
</body>
</html>